fix: update Title of service
Steinbeck-Lab/cheminformatics-python-microservice pull request #366
Opened 2023-09-04 14:13 UTC by Kohulan

2023-09-04 14:15 UTC, CS76 requested changes

2023-09-04 14:15 UTC, CS76 commented on public/img/logo.png
@Kohulan let's retain the original logo typeface and remove the word python. Changing the typeface is not advisable especially since we uploaded everything to Chemarxiv etc.

2023-09-04 14:20 UTC, Kohulan commented on public/img/logo.png
I could update the font but Chemrxiv is not a problem since it is a preprint. Do you still want to stick to the old font?

2023-09-04 14:21 UTC, CS76 commented on public/img/logo.png
let's stick to the old font, please.

2023-09-04 14:28 UTC, Kohulan commented on public/img/logo.png
Done now.

2023-09-04 14:29 UTC, CS76 approved these changes

2023-09-05 07:55 UTC, NishaSharma14 approved these changes

2023-09-05 07:56 UTC, merged